### ISSUE TITLE
R package download - can't resolve url

### ISSUE THREAD

**Issue by lwasser** [earthlab/r-python-eds-lessons-env#4]
@jvtcl

Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)
Warning: unable to access index for repository http://cran.us.r-project.org/src/contrib:
  cannot open URL 'http://cran.us.r-project.org/src/contrib/PACKAGES'
Installing package microbenchmark 

Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)
Warning: unable to access index for repository http://cran.us.r-project.org/src/contrib:
  cannot open URL 'http://cran.us.r-project.org/src/contrib/PACKAGES'
There were 19 warnings (use warnings() to see them)
Error: Installation of package(s) dplyr, ff, ggplot2, ggmap, gridExtra, knitr, maps, raster, rasterVis, rgdal, rgeos, RJSONIO, rmarkdown, RSAGA, rtweet, sf, stringr, widyr, microbenchmark was unsuccessful.
Execution halted

**Comment by jvtcl** [comment]
This is due to a CRAN outage -- confirmed by checking local `install.packages` on a couple of other machines. I'll check whether it's back up later on!

**Comment by lwasser** [comment]
thank you @jvtcl ... figures this happens while trying to revisit our envt build.
